# Generated by Django 3.2.9 on 2022-02-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='imageurl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageurl',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Charles', max_length=200),
        ),
    ]
